from sqlalchemy import Column, Integer, String, Integer
from database import Base

class Habilidad(Base):
    __tablename__ = "habilidades"

    id = Column(Integer, primary_key=True, index=True)

    # Datos generales
    career = Column(String)
    title = Column(String)
    company = Column(String)
    workday = Column(String)
    modality = Column(String)
    salary = Column(String)

    # Habilidades técnicas (hard)
    hard_python = Column(Integer)
    hard_java = Column(Integer)
    hard_sql = Column(Integer)
    hard__net = Column(Integer)
    hard_javascript = Column(Integer)
    hard_html = Column(Integer)
    hard_css = Column(Integer)
    hard_django = Column(Integer)
    hard_flask = Column(Integer)
    hard_react = Column(Integer)
    hard_angular = Column(Integer)
    hard_node = Column(Integer)
    hard_power_bi = Column(Integer)
    hard_sap = Column(Integer)
    hard_aws = Column(Integer)
    hard_azure = Column(Integer)
    hard_git = Column(Integer)
    hard_github = Column(Integer)
    hard_ci_cd = Column(Integer)
    hard_linux = Column(Integer)
    hard_docker = Column(Integer)
    hard_kubernetes = Column(Integer)
    hard_etl = Column(Integer)
    hard_big_data = Column(Integer)
    hard_data_lake = Column(Integer)
    hard_postgresql = Column(Integer)
    hard_mysql = Column(Integer)
    hard_nosql = Column(Integer)
    hard_mongodb = Column(Integer)
    hard_cloud = Column(Integer)
    hard_bash = Column(Integer)
    hard_jira = Column(Integer)
    hard_excel = Column(Integer)
    hard_autocad = Column(Integer)
    hard_r = Column(Integer)
    hard_office = Column(Integer)
    hard_google_workspace = Column(Integer)
    hard_matlab = Column(Integer)
    hard_project = Column(Integer)
    hard_solidworks = Column(Integer)
    hard_Manejo_de_datos = Column(Integer)
    hard_seguridad = Column(Integer)
    hard_desarrollo_web = Column(Integer)
    hard_gestión_proyectos = Column(Integer)
    hard_Mejora_procesos = Column(Integer)

    # Habilidades blandas (soft)
    soft_comunicación = Column(Integer)
    soft_trabajo_en_equipo = Column(Integer)
    soft_proactividad = Column(Integer)
    soft_compromiso = Column(Integer)
    soft_adaptabilidad = Column(Integer)
    soft_liderazgo = Column(Integer)
    soft_responsabilidad = Column(Integer)
    soft_creatividad = Column(Integer)
    soft_resolución_de_problemas = Column(Integer)
    soft_orientación_al_cliente = Column(Integer)
    soft_pensamiento_crítico = Column(Integer)

